#!/bin/bash

# Creation de la clef ./build_svprognu -d /dev/sdX
# Creation de l'iso seule ./build_svprognu

set -e

ISO="live_svpro_gnu-amd64.hybrid.iso"

# Recuperation iso
echo "Téléchargement de l'iso..."
sleep 5
wget -O ${ISO} https://www.weblib.re/dokuwiki/_media/svpro_gnu:live_svpro_gnu-amd64.hybrid.iso
wget -O ${ISO}.md5sum https://www.weblib.re/dokuwiki/_media/svpro_gnu:live_svpro_gnu-amd64.hybrid.iso.md5sum
echo "Vérification de l'image..."

if ! md5sum -c ${ISO}.md5sum
	then
	echo "ISO Corompue. Abandon !!"
	rm -f ${ISO} ${ISO}.md5
	exit 1
fi

# Copie de l'image iso sur clé
while getopts ":d: " opt; do
case $opt in
   d)
	echo "Transfert en cours..."
	dd if=${ISO} of=$OPTARG bs=4M status=progress
	sync

	# Création de la partition dédiée à la persistence
	echo "Création de la persistence..."
	sleep 10
	printf 'n\np\n\n\n\nw' | fdisk $OPTARG
	echo "Formatage..."
	sleep 10
	mkfs.ext4 -L persistence ${OPTARG}3

	# Configuratio de la partition
	mkdir -p ./tmp
	mount ${OPTARG}3 ./tmp
	echo "/ union" > ./tmp/persistence.conf
	umount ./tmp
	echo "Finalisation..."
	sleep 10
	rm -rf ./tmp

	# Fin
	echo "Terminé ! Vous pouvez booter sur la clé USB, la persistence sera auto-configurée lors du premier Boot !"
	;;

esac
done

exit 0
