#!/bin/bash

# stick_build /dev/sdX

set -e

ISO="live_svpro_gnu-amd64.hybrid.iso"

# Recuperation iso
echo "Téléchargement de l'iso..."
sleep 5
wget -O ${ISO} https://cloud.weblib.re/s/iZ3RPAbJ7BXTmXc/download
wget -O ${ISO}.md5sum https://cloud.weblib.re/s/GtSEtc4Gy8CGxFW/download
echo "Vérification de l'image..."

if ! md5sum -c ${ISO}.md5sum
	then
	echo "ISO Corompue. Abandon !!"
	rm -f ${ISO} ${ISO}.md5
	exit 1
fi

# Copie de l'image iso sur clé
echo "Transfert en cours..."
dd if=${ISO} of=$1 bs=4M status=progress
sync

# Création de la partition dédiée à la persistence
echo "Création de la persistence..."
sleep 5
printf 'n\np\n\n\n\nw' | fdisk $1
mkfs.ext4 -L persistence ${1}3

# Configuratio de la partition
mount ${1}3 /mnt
echo / union > /mnt/persistence.conf
umount /mnt

# Fin
echo "Terminé ! Vous pouvez booter sur la clé USB, la persistence sera auto-configurée lors du premier Boot !"


exit 0
