// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1594475138);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1594475289);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 16348);
user_pref("browser.cache.disk.capacity", 542720);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "FR");
user_pref("calendar.list.sortOrder", "37c26703-b06d-4ca5-a71b-1f844bda8993");
user_pref("calendar.registry.37c26703-b06d-4ca5-a71b-1f844bda8993.calendar-main-in-composite", true);
user_pref("calendar.registry.37c26703-b06d-4ca5-a71b-1f844bda8993.name", "Mon agenda");
user_pref("calendar.registry.37c26703-b06d-4ca5-a71b-1f844bda8993.type", "storage");
user_pref("calendar.registry.37c26703-b06d-4ca5-a71b-1f844bda8993.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Paris");
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1594482218);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200629235513");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.webextensions.uuids", "{\"{e2fda1a4-762b-4020-b5ad-a41df1933103}\":\"f228227a-c9cc-4c35-92ec-4c40a5b44a49\",\"default-theme@mozilla.org\":\"14198eea-f337-497e-a8a4-606610528341\",\"google@search.mozilla.org\":\"ed44e6d4-b65e-4435-8ff3-f3123c172ab6\",\"bing@search.mozilla.org\":\"8e868fa9-ce0a-43fe-9eaf-8d92e9b28c08\",\"amazon@search.mozilla.org\":\"24815bc5-be04-4d77-98b4-a8d115c298e6\",\"ddg@search.mozilla.org\":\"cd3a95f4-315e-40a0-806d-adeff365aa01\",\"qwant@search.mozilla.org\":\"5931d4a9-3292-4157-9d1d-85ca5de4b2c5\",\"wikipedia@search.mozilla.org\":\"88f5b6f8-a687-4022-8399-0736f5349615\",\"{847b3a00-7ab1-11d4-8f02-006008948af5}\":\"9bbf4588-bfcf-4698-aeca-6791a53213a0\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.rights.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "1a9b80e8-1815-4640-8add-9ebb228391e");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Travail");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personnel");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "À faire");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "En attente");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("places.history.expiration.transient_current_max_pages", 111257);
user_pref("security.sandbox.plugin.tempDirSuffix", "619ccaba-8a02-460f-8fcb-c3205ff79c1f");
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_update_seconds", 1594475289);
user_pref("services.settings.main.hijack-blocklists.last_check", 1594475289);
user_pref("services.settings.main.language-dictionaries.last_check", 1594475289);
user_pref("services.settings.main.sites-classification.last_check", 1594475289);
user_pref("services.settings.security.onecrl.checked", 1594475289);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "d06e102e-420e-425b-b6b0-ddd3933da9af");
user_pref("toolkit.telemetry.prompted", 2);
